mode: "dev"
port: 9003

log:
  level: "debug"
  filename: "./log/blog.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5
mysql:
  host: 127.0.0.1
  port: 3306
  user: wanart
  password: wanart
  db: ginsql
  max_open_conns: 100
  max_idle_conns: 20